spring:
  main:
    show-banner: false

#server:
#  port: 8443
#  ssl:
#    key-store: file:///Users/gireeshbabu/workspace/work/keys/mykeys.jks
#    key-store-password: letmein
#    key-password: letmein